[package]
name = "template"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = "symbols"
panic = "abort"
opt-level = "z"

[dependencies]
windows = { version = "0.59.0", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_Security"] }